CREATE INDEX idx_pid_provider_pidstore_pid ON pidstore_pid (pid_provider);
CREATE INDEX idx_pos_pidstore_pid ON pidstore_pid (pid_type, object_uuid, status,);
CREATE INDEX idx_item_type_id_item_type_mapping ON item_type_mapping (item_type_id);
CREATE INDEX idx_created_item_type_mapping ON item_type_mapping (created);
CREATE INDEX idx_isvalid_oaiserver_schema ON oaiserver_schema (isvalid);
CREATE INDEX idx_child_id_pidrelations_pidrelation ON pidrelations_pidrelation (child_id);
CREATE INDEX idx_parent_index ON index (parent);
CREATE INDEX idx_item_type_id_item_metadata ON item_metadata (item_type_id);
CREATE INDEX idx_pid_type_object_uuid_pidstore_pid ON pidstore_pid (pid_type,object_uuid);
CREATE INDEX idx_object_uuid_pidstore_pid ON pidstore_pid(object_uuid);
CREATE INDEX idx_id_relation_type_pidrelation ON pidrelations_pidrelation(parent_id, child_id, relation_type);
CREATE INDEX idx_public_index ON index ( public_state , public_date,harvest_public_state);
CREATE INDEX idx_harvest_spec_index ON index (harvest_spec, parent);
CREATE INDEX idx_delflg_item_type_property ON item_type_property (delflg);
CREATE INDEX idx_id_delflg_item_type_property ON item_type_property (id,delflg);
CREATE INDEX idx_registerd_admin_lang_settings ON admin_lang_settings (is_registered);
CREATE INDEX idx_mapping_item_type_mapping ON item_type_mapping using gin (mapping);
CREATE INDEX idx_group_state_accounts_group_members ON accounts_group_members (group_id,state);
CREATE INDEX idx_is_deleted_item_type ON item_type (is_deleted);
CREATE INDEX idx_admin_type_id_accounts_group_admin ON accounts_group_admin(admin_id,admin_type);
