# -*- coding: utf-8 -*-
#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#

version: "3.2"

services:
    stage_1:
        build:
            context: .
            target: stage_1
        environment:
            - PATH=/home/invenio/.virtualenvs/invenio/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
            - INVENIO_WEB_HOST=127.0.0.1
            - INVENIO_WEB_INSTANCE=invenio
            - INVENIO_WEB_VENV=invenio
            - INVENIO_WEB_HOST_NAME=weko3.repo.nii.ac.jp
            - INVENIO_WEB_PROTOCOL=https
            - INVENIO_USER_EMAIL=wekosoftware@nii.ac.jp
            - INVENIO_USER_PASS=uspass123
            - INVENIO_POSTGRESQL_HOST=postgresql
            - INVENIO_POSTGRESQL_DBNAME=invenio
            - INVENIO_POSTGRESQL_DBUSER=invenio
            - INVENIO_POSTGRESQL_DBPASS=dbpass123
            - INVENIO_REDIS_HOST=redis
            - INVENIO_ELASTICSEARCH_HOST=elasticsearch
            - INVENIO_RABBITMQ_HOST=rabbitmq
            - INVENIO_RABBITMQ_USER=guest
            - INVENIO_RABBITMQ_PASS=guest
            - INVENIO_RABBITMQ_VHOST=/
            - INVENIO_WORKER_HOST=127.0.0.1
            - INVENIO_FILES_LOCATION_NAME=local
            - INVENIO_FILES_LOCATION_URI=/var/tmp
            - INVENIO_ROLE_SYSTEM=System Administrator
            - INVENIO_ROLE_REPOSITORY=Repository Administrator
            - INVENIO_ROLE_CONTRIBUTOR=Contributor
            - INVENIO_ROLE_COMMUNITY=Community Administrator
            # production or development
            - FLASK_ENV=development
            - FLASK_DEBUG=True
            - SEARCH_INDEX_PREFIX=tenant1
            - INVENIO_DB_POOL_CLASS=QueuePool
            - GOOGLE_TRACKING_ID_SYSTEM=
            - GOOGLE_TRACKING_ID_USER=
            - CACHE_REDIS_DB=0
            - ACCOUNTS_SESSION_REDIS_DB_NO=1
            - CELERY_RESULT_BACKEND_DB_NO=2
            - WEKO_AGGREGATE_EVENT_HOUR=0
            - WEKO_AGGREGATE_EVENT_MINUTE=0
            - WEKO_HANDLE_ALLOW_REGISTER_CRNI=False
            - WEKO_RECORDS_UI_SECRET_KEY="secret"
            - SECRET_KEY="CHANGE ME"
            - WTF_CSRF_SECRET_KEY="CHANGE ME"
        volumes:
            - weko3_data:/var/tmp
            - static_data:/home/invenio/.virtualenvs/invenio/var/instance/static
            - data_data:/home/invenio/.virtualenvs/invenio/var/instance/data
            - conf_data:/home/invenio/.virtualenvs/invenio/var/instance/conf
            - type: bind
              source: .
              target: /code
            - /code/modules/invenio-admin/invenio_admin.egg-info
            - /code/modules/invenio-app/invenio_app.egg-info
            - /code/modules/invenio-oauth2server/invenio_oauth2server.egg-info
            - /code/modules/invenio-files-rest/invenio_files_rest.egg-info
            - /code/modules/invenio-s3/invenio_s3.egg-info
            - /code/modules/invenio-oaiharvester/invenio_oaiharvester.egg-info
            - /code/modules/invenio-oaiserver/invenio_oaiserver.egg-info
            - /code/modules/invenio-records/invenio_records.egg-info
            - /code/modules/invenio-previewer/invenio_previewer.egg-info
            - /code/modules/invenio-stats/invenio_stats.egg-info
            - /code/modules/invenio-records-rest/invenio_records_rest.egg-info
            - /code/modules/invenio-communities/invenio_communities.egg-info
            - /code/modules/invenio-mail/invenio_mail.egg-info
            - /code/modules/invenio-deposit/invenio_deposit.egg-info
            - /code/modules/invenio-resourcesyncserver/invenio_resourcesyncserver.egg-info
            - /code/modules/invenio-resourcesyncclient/invenio_resourcesyncclient.egg-info
            - /code/modules/invenio-queues/invenio_queues.egg-info
            - /code/modules/invenio-db/invenio_db.egg-info
            - /code/modules/weko-theme/weko_theme.egg-info
            - /code/modules/weko-itemtypes-ui/weko_itemtypes_ui.egg-info
            - /code/modules/weko-items-ui/weko_items_ui.egg-info
            - /code/modules/weko-accounts/weko_accounts.egg-info
            - /code/modules/weko-admin/weko_admin.egg-info
            - /code/modules/weko-logging/weko_logging.egg-info
            - /code/modules/weko-gridlayout/weko_gridlayout.egg-info
            - /code/modules/weko-groups/weko_groups.egg-info
            - /code/modules/weko-search-ui/weko_search_ui.egg-info
            - /code/modules/weko-records/weko_records.egg-info
            - /code/modules/weko-records-ui/weko_records_ui.egg-info
            - /code/modules/weko-schema-ui/weko_schema_ui.egg-info
            - /code/modules/weko-index-tree/weko_index_tree.egg-info
            - /code/modules/weko-user-profiles/weko_user_profiles.egg-info
            - /code/modules/weko-deposit/weko_deposit.egg-info
            - /code/modules/weko-authors/weko_authors.egg-info
            - /code/modules/weko-handle/weko_handle.egg-info
            - /code/modules/weko-workflow/weko_workflow.egg-info
            - /code/modules/weko-indextree-journal/weko_indextree_journal.egg-info
            - /code/modules/weko-bulkupdate/weko_bulkupdate.egg-info
            - /code/modules/weko-items-autofill/weko_items_autofill.egg-info
            - /code/modules/weko-sitemap/weko_sitemap.egg-info
            - /code/modules/invenio-iiif/invenio_iiif.egg-info
        user: invenio
        image: weko.stage_1:latest
    stage_2:
        build:
            context: .
            target: stage_2
        image: weko.stage_2:latest
    stage_3:
        build:
            context: .
            target: stage_3
        image: weko.stage_3:latest
    stage_4:
        build:
            context: .
            target: stage_4
        image: weko.stage_4:latest
    stage_5:
        build:
            context: .
            target: stage_5
        image: weko.stage_5:latest
    stage_6:
        build:
            context: .
            target: stage_6
        image: weko.stage_6:latest
    stage_7:
        build:
            context: .
            target: stage_7
        image: weko.stage_7:latest
    stage_8:
        build:
            context: .
            target: stage_8
        image: weko:latest
    elasticsearch:
        build:
          context: .
          dockerfile: ./elasticsearch/Dockerfile
        image: elasticsearch:latest
    nginx:
        build:
          context: ./nginx
          target: nginx-with-shib
        image: nginx-with-shib:latest
