#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""add affiliation"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e471f74f4f27'
down_revision = '5872b2d73941'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors_affiliation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('scheme', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors_affiliation_settings')),
    sa.UniqueConstraint('id', name=op.f('uq_authors_affiliation_settings_id')),
    sa.UniqueConstraint('scheme', name=op.f('uq_authors_affiliation_settings_scheme'))
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors_affiliation_settings')
    # ### end Alembic commands ###
