# coding:utf-8
"""Default item type."""
from properties import AddProperty
from . import item_type_config as config

item_type_id = config.DEFAULT_CONFERENCE_PAPER
item_type_name = "default_会議発表論文 / Conference Paper"
property_list = [
    AddProperty(
        AddProperty.title,
        'タイトル',
        'タイトル',
        'Title',
        required=True,
        multiple=True,
        showlist=True,
        newline=True
    ),
    AddProperty(
        AddProperty.language,
        '言語',
        '言語',
        'Language',
        required=True,
        multiple=True
    ),
    AddProperty(
        AddProperty.subject,
        'キーワード',
        'キーワード',
        'Keyword',
        multiple=True
    ),
    AddProperty(
        AddProperty.resource_type,
        '資源タイプ',
        '資源タイプ',
        'Resource Type',
        required=True
    ),
    AddProperty(
        AddProperty.identifier_registration,
        'ID登録',
        'ID登録',
        'Identifier Registration'
    ),
    AddProperty(
        AddProperty.access_right,
        'アクセス権',
        'アクセス権',
        'Access Right'
    ),
    AddProperty(
        AddProperty.alternative_title,
        'その他のタイトル',
        'その他のタイトル',
        'Alternative Title',
        multiple=True
    ),
    AddProperty(
        AddProperty.creator,
        '著者',
        '著者',
        'Creator',
        multiple=True,
        showlist=True,
        newline=True
    ),
    AddProperty(
        AddProperty.full_name,
        '著者（英）',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.description,
        '著者ID',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.description,
        '抄録',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.description,
        '内容記述',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.biblio_info,
        '書誌情報',
        '',
        '',
        showlist=True
    ),
    AddProperty(
        AddProperty.publisher,
        '出版者',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.source_id,
        'ISSN',
        '',
        ''
    ),
    AddProperty(
        AddProperty.relation,
        'ISBN',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.source_id,
        '書誌レコードID',
        '',
        ''
    ),
    AddProperty(
        AddProperty.relation,
        '書誌レコードID',
        '',
        ''
    ),
    AddProperty(
        AddProperty.relation,
        '論文ID（NAID）',
        '',
        ''
    ),
    AddProperty(
        AddProperty.relation,
        'PubMed番号',
        '',
        ''
    ),
    AddProperty(
        AddProperty.relation,
        'DOI',
        '',
        ''
    ),
    AddProperty(
        AddProperty.rights,
        '権利',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.relation,
        '情報源',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.relation,
        '関連サイト',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.relation,
        '他の資源との関係',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.description,
        'フォーマット',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.version_type,
        '著者版フラグ',
        '',
        ''
    ),
    AddProperty(
        AddProperty.subject,
        '日本十進分類法',
        '',
        '',
        multiple=True
    ),
    AddProperty(
        AddProperty.files,
        'ファイル情報',
        'ファイル情報',
        'File Info',
        multiple=True,
        showlist=True
    ),
    AddProperty(
        AddProperty.heading,
        '見出し',
        '',
        '',
        multiple=True
    )
]