DEFAULT_ITEM_TYPE_SIMPLE = "30001"
DEFAULT_ITEM_TYPE_FULL = "30002"

EXCLUSION_LIST = []
# Exclusion property id list. The ID set in the list will not be registered.
# e.g.: EXCLUSION_LIST = [30001, 30002] or EXCLUSION_LIST = [DEFAULT_ITEM_TYPE_SIMPLE, DEFAULT_ITEM_TYPE_FULL]

HARVESTING_ITEM_TYPE_LIST = []