# conftest.py
import pytest

# language code list
language_val3 = [
    None,
    "jpn",
    "eng",
    "aar",
    "abk",
    "afr",
    "aka",
    "amh",
    "ara",
    "arg",
    "asm",
    "ava",
    "ave",
    "aym",
    "aze",
    "bak",
    "bam",
    "bel",
    "ben",
    "bis",
    "bod",
    "bos",
    "bre",
    "bul",
    "cat",
    "ces",
    "cha",
    "che",
    "chu",
    "chv",
    "cor",
    "cos",
    "cre",
    "cym",
    "dan",
    "deu",
    "div",
    "dzo",
    "ell",
    "epo",
    "est",
    "eus",
    "ewe",
    "fao",
    "fas",
    "fij",
    "fin",
    "fra",
    "fry",
    "ful",
    "gla",
    "gle",
    "glg",
    "glv",
    "grn",
    "guj",
    "hat",
    "hau",
    "heb",
    "her",
    "hin",
    "hmo",
    "hrv",
    "hun",
    "hye",
    "ibo",
    "ido",
    "iii",
    "iku",
    "ile",
    "ina",
    "ind",
    "ipk",
    "isl",
    "ita",
    "jav",
    "kal",
    "kan",
    "kas",
    "kat",
    "kau",
    "kaz",
    "khm",
    "kik",
    "kin",
    "kir",
    "kom",
    "kon",
    "kor",
    "kua",
    "kur",
    "lao",
    "lat",
    "lav",
    "lim",
    "lin",
    "lit",
    "ltz",
    "lub",
    "lug",
    "mah",
    "mal",
    "mar",
    "mkd",
    "mlg",
    "mlt",
    "mon",
    "mri",
    "msa",
    "mya",
    "nau",
    "nav",
    "nbl",
    "nde",
    "ndo",
    "nep",
    "nld",
    "nno",
    "nob",
    "nor",
    "nya",
    "oci",
    "oji",
    "ori",
    "orm",
    "oss",
    "pan",
    "pli",
    "pol",
    "por",
    "pus",
    "que",
    "roh",
    "ron",
    "run",
    "rus",
    "sag",
    "san",
    "sin",
    "slk",
    "slv",
    "sme",
    "smo",
    "sna",
    "snd",
    "som",
    "sot",
    "spa",
    "sqi",
    "srd",
    "srp",
    "ssw",
    "sun",
    "swa",
    "swe",
    "tah",
    "tam",
    "tat",
    "tel",
    "tgk",
    "tgl",
    "tha",
    "tir",
    "ton",
    "tsn",
    "tso",
    "tuk",
    "tur",
    "twi",
    "uig",
    "ukr",
    "urd",
    "uzb",
    "ven",
    "vie",
    "vol",
    "wln",
    "wol",
    "xho",
    "yid",
    "yor",
    "zha",
    "zho",
    "zul",
]

# title map
title_map = [
    {"name": "jpn", "value": "jpn"},
    {"name": "eng", "value": "eng"},
    {"name": "aar", "value": "aar"},
    {"name": "abk", "value": "abk"},
    {"name": "afr", "value": "afr"},
    {"name": "aka", "value": "aka"},
    {"name": "amh", "value": "amh"},
    {"name": "ara", "value": "ara"},
    {"name": "arg", "value": "arg"},
    {"name": "asm", "value": "asm"},
    {"name": "ava", "value": "ava"},
    {"name": "ave", "value": "ave"},
    {"name": "aym", "value": "aym"},
    {"name": "aze", "value": "aze"},
    {"name": "bak", "value": "bak"},
    {"name": "bam", "value": "bam"},
    {"name": "bel", "value": "bel"},
    {"name": "ben", "value": "ben"},
    {"name": "bis", "value": "bis"},
    {"name": "bod", "value": "bod"},
    {"name": "bos", "value": "bos"},
    {"name": "bre", "value": "bre"},
    {"name": "bul", "value": "bul"},
    {"name": "cat", "value": "cat"},
    {"name": "ces", "value": "ces"},
    {"name": "cha", "value": "cha"},
    {"name": "che", "value": "che"},
    {"name": "chu", "value": "chu"},
    {"name": "chv", "value": "chv"},
    {"name": "cor", "value": "cor"},
    {"name": "cos", "value": "cos"},
    {"name": "cre", "value": "cre"},
    {"name": "cym", "value": "cym"},
    {"name": "dan", "value": "dan"},
    {"name": "deu", "value": "deu"},
    {"name": "div", "value": "div"},
    {"name": "dzo", "value": "dzo"},
    {"name": "ell", "value": "ell"},
    {"name": "epo", "value": "epo"},
    {"name": "est", "value": "est"},
    {"name": "eus", "value": "eus"},
    {"name": "ewe", "value": "ewe"},
    {"name": "fao", "value": "fao"},
    {"name": "fas", "value": "fas"},
    {"name": "fij", "value": "fij"},
    {"name": "fin", "value": "fin"},
    {"name": "fra", "value": "fra"},
    {"name": "fry", "value": "fry"},
    {"name": "ful", "value": "ful"},
    {"name": "gla", "value": "gla"},
    {"name": "gle", "value": "gle"},
    {"name": "glg", "value": "glg"},
    {"name": "glv", "value": "glv"},
    {"name": "grn", "value": "grn"},
    {"name": "guj", "value": "guj"},
    {"name": "hat", "value": "hat"},
    {"name": "hau", "value": "hau"},
    {"name": "heb", "value": "heb"},
    {"name": "her", "value": "her"},
    {"name": "hin", "value": "hin"},
    {"name": "hmo", "value": "hmo"},
    {"name": "hrv", "value": "hrv"},
    {"name": "hun", "value": "hun"},
    {"name": "hye", "value": "hye"},
    {"name": "ibo", "value": "ibo"},
    {"name": "ido", "value": "ido"},
    {"name": "iii", "value": "iii"},
    {"name": "iku", "value": "iku"},
    {"name": "ile", "value": "ile"},
    {"name": "ina", "value": "ina"},
    {"name": "ind", "value": "ind"},
    {"name": "ipk", "value": "ipk"},
    {"name": "isl", "value": "isl"},
    {"name": "ita", "value": "ita"},
    {"name": "jav", "value": "jav"},
    {"name": "kal", "value": "kal"},
    {"name": "kan", "value": "kan"},
    {"name": "kas", "value": "kas"},
    {"name": "kat", "value": "kat"},
    {"name": "kau", "value": "kau"},
    {"name": "kaz", "value": "kaz"},
    {"name": "khm", "value": "khm"},
    {"name": "kik", "value": "kik"},
    {"name": "kin", "value": "kin"},
    {"name": "kir", "value": "kir"},
    {"name": "kom", "value": "kom"},
    {"name": "kon", "value": "kon"},
    {"name": "kor", "value": "kor"},
    {"name": "kua", "value": "kua"},
    {"name": "kur", "value": "kur"},
    {"name": "lao", "value": "lao"},
    {"name": "lat", "value": "lat"},
    {"name": "lav", "value": "lav"},
    {"name": "lim", "value": "lim"},
    {"name": "lin", "value": "lin"},
    {"name": "lit", "value": "lit"},
    {"name": "ltz", "value": "ltz"},
    {"name": "lub", "value": "lub"},
    {"name": "lug", "value": "lug"},
    {"name": "mah", "value": "mah"},
    {"name": "mal", "value": "mal"},
    {"name": "mar", "value": "mar"},
    {"name": "mkd", "value": "mkd"},
    {"name": "mlg", "value": "mlg"},
    {"name": "mlt", "value": "mlt"},
    {"name": "mon", "value": "mon"},
    {"name": "mri", "value": "mri"},
    {"name": "msa", "value": "msa"},
    {"name": "mya", "value": "mya"},
    {"name": "nau", "value": "nau"},
    {"name": "nav", "value": "nav"},
    {"name": "nbl", "value": "nbl"},
    {"name": "nde", "value": "nde"},
    {"name": "ndo", "value": "ndo"},
    {"name": "nep", "value": "nep"},
    {"name": "nld", "value": "nld"},
    {"name": "nno", "value": "nno"},
    {"name": "nob", "value": "nob"},
    {"name": "nor", "value": "nor"},
    {"name": "nya", "value": "nya"},
    {"name": "oci", "value": "oci"},
    {"name": "oji", "value": "oji"},
    {"name": "ori", "value": "ori"},
    {"name": "orm", "value": "orm"},
    {"name": "oss", "value": "oss"},
    {"name": "pan", "value": "pan"},
    {"name": "pli", "value": "pli"},
    {"name": "pol", "value": "pol"},
    {"name": "por", "value": "por"},
    {"name": "pus", "value": "pus"},
    {"name": "que", "value": "que"},
    {"name": "roh", "value": "roh"},
    {"name": "ron", "value": "ron"},
    {"name": "run", "value": "run"},
    {"name": "rus", "value": "rus"},
    {"name": "sag", "value": "sag"},
    {"name": "san", "value": "san"},
    {"name": "sin", "value": "sin"},
    {"name": "slk", "value": "slk"},
    {"name": "slv", "value": "slv"},
    {"name": "sme", "value": "sme"},
    {"name": "smo", "value": "smo"},
    {"name": "sna", "value": "sna"},
    {"name": "snd", "value": "snd"},
    {"name": "som", "value": "som"},
    {"name": "sot", "value": "sot"},
    {"name": "spa", "value": "spa"},
    {"name": "sqi", "value": "sqi"},
    {"name": "srd", "value": "srd"},
    {"name": "srp", "value": "srp"},
    {"name": "ssw", "value": "ssw"},
    {"name": "sun", "value": "sun"},
    {"name": "swa", "value": "swa"},
    {"name": "swe", "value": "swe"},
    {"name": "tah", "value": "tah"},
    {"name": "tam", "value": "tam"},
    {"name": "tat", "value": "tat"},
    {"name": "tel", "value": "tel"},
    {"name": "tgk", "value": "tgk"},
    {"name": "tgl", "value": "tgl"},
    {"name": "tha", "value": "tha"},
    {"name": "tir", "value": "tir"},
    {"name": "ton", "value": "ton"},
    {"name": "tsn", "value": "tsn"},
    {"name": "tso", "value": "tso"},
    {"name": "tuk", "value": "tuk"},
    {"name": "tur", "value": "tur"},
    {"name": "twi", "value": "twi"},
    {"name": "uig", "value": "uig"},
    {"name": "ukr", "value": "ukr"},
    {"name": "urd", "value": "urd"},
    {"name": "uzb", "value": "uzb"},
    {"name": "ven", "value": "ven"},
    {"name": "vie", "value": "vie"},
    {"name": "vol", "value": "vol"},
    {"name": "wln", "value": "wln"},
    {"name": "wol", "value": "wol"},
    {"name": "xho", "value": "xho"},
    {"name": "yid", "value": "yid"},
    {"name": "yor", "value": "yor"},
    {"name": "zha", "value": "zha"},
    {"name": "zho", "value": "zho"},
    {"name": "zul", "value": "zul"}
]


default_schema = {
    "type": "object",
    "format": "object",
    "title": "original_language",
    "properties": {
        "original_language": {
            "type": ["null", "string"],
            "format": "select",
            "title": "Original Language",
            "enum": language_val3
        },
    },
}

default_post_data = {
    "table_row_map": {
        "form": [
            {
                "items": [
                    {
                        "key": "item_original_lang[].original_language",
                        "type": "select",
                        "titleMap": title_map,
                        "title": "原文の言語",
                        "title_i18n": {"ja": "原文の言語", "en": "Original Language"}
                    }
                ],
                "key": "item_original_lang",
                "add": "New",
                "style": {"add": "btn-success"},
                "title": "原文の言語",
                "title_i18n": {"ja": "原文の言語", "en": "Original Language"}
            }
        ],
        "schema": {
            "properties": {
                "item_original_lang": {
                    "type": "array",
                    "title": "原文の言語",
                    "minItems": "1",
                    "maxItems": "9999",
                    "items": default_schema
                }
            },
            "required": []
        },
        "mapping": {
            "item_original_lang": {
                "display_lang_type": "",
                "jpcoar_v1_mapping": "",
                "jpcoar_mapping": {
                    "originalLanguage": {
                        "@value": "original_language",
                        "@attributes": {"xml:lang": "original_language_language"},
                    }
                },
                "junii2_mapping": "",
                "lido_mapping": "",
                "lom_mapping": "",
                "oai_dc_mapping": "",
                "spase_mapping": "",
            }
        }
    },
    "table_row": ["item_original_lang"],
    "meta_system": {},
    "meta_list": {
        "item_original_lang": {
            "title": "原文の言語",
            "title_i18n": {"ja": "原文の言語", "en": "Original Language"},
            "input_type": "cus_1052",
            "input_value": "",
            "option": {
                "required": False,
                "multiple": True,
                "hidden": False,
                "showlist": False,
                "crtf": False,
                "oneline": False,
            },
            "input_minItems": "1",
            "input_maxItems": "9999"
        }
    },
    "schemaeditor": {
        "schema": {
            "item_original_lang": default_schema
        }
    },
    "edit_notes": {
        "item_original_lang": ""
    }
}
