--
-- Delete data Restricted access.
--


truncate public.mail_templates;

--
-- Data for Name: mail_templates; Type: TABLE DATA; Schema: public; Owner: invenio
--

COPY public.mail_templates (id, mail_subject, mail_body, default_mail) FROM stdin;
1	利用申請登録のご案内／Register Application for Use	[restricted_site_name_ja]です。\n下記のリンクにアクセスしていただき、利用申請の登録を行ってください。\n\n[url_guest_user]\n\nこのメールは自動送信されているので返信しないでください。\nお問い合わせは下記までお願いします。また、このメールに心当たりのない方は、[restricted_site_name_ja]までご連絡ください。\n\n[restricted_site_name_ja]：[restricted_site_url]\n問い合わせ窓口：[restricted_site_mail]\n\n----------------------------------------------------------------------------------\n\nThis is a message from [restricted_site_name_en].\nPlease access the link below and register your Application.\n\n[url_guest_user]\n\nPlease do not reply to this email as it has been sent automatically.\nPlease direct all inquiries to the following address.\nAlso, if you received this message in error, please notify [restricted_site_name_en].\n\n[restricted_site_name_en]：[restricted_site_url]\nE-mail：[restricted_site_mail]	t
2	データ利用申請の受付のお知らせ／Your Application was Received	[restricted_university_institution]\n[restricted_fullname]　様\n\n[restricted_institution_name_ja]です。\n[restricted_site_name_ja]をご利用いただいて、ありがとうございます。\n\n下記の利用申請を受け付けました。\n\n申請番号： [restricted_activity_id]\n登録者名： [restricted_fullname]\nメールアドレス： [restricted_mail_address]\n所属機関：[restricted_university_institution]\n研究題目：[restricted_research_title]\n申請データ：[restricted_data_name]\n申請年月日：[restricted_application_date]\n\n[restricted_institution_name_ja]で審査しますので、結果の連絡をお待ちください。\n\nこのメールは自動送信されているので返信しないでください。\nお問い合わせは下記までお願いします。また、このメールに心当たりのない方は、[restricted_institution_name_ja]までご連絡ください。\n\n[restricted_site_name_ja]：[restricted_site_url]\n問い合わせ窓口：[restricted_site_mail]\n\n----------------------------------------------------------------------------------\n\nDear [restricted_fullname],\n\nThis is a message from [restricted_institution_name_en].\nThank you for using [restricted_site_name_en].\n\nWe received the below application:\n\nApplication No.：[restricted_activity_id]\nName：[restricted_fullname]\nE-mail：[restricted_mail_address]\nAffiliation：[restricted_university_institution]\nTitle of research：[restricted_research_title]\nDataset requested ：[restricted_data_name]\nApplication date：[restricted_application_date]\n\nYou will be notified once the application is approved. \n\nPlease do not reply to this email as it has been sent automatically.\nPlease direct all inquiries to the following address.\nAlso, if you received this message in error, please notify [restricted_institution_name_en].\n\n[restricted_site_name_en]：[restricted_site_url]\nE-mail：[restricted_site_mail]	t
3	利用申請の承認のお願い／Request for Approval of Application for Use	[restricted_site_name_ja]です。下記の方から利用申請がありました。\n\n申請番号： [restricted_activity_id]\n登録者名： [restricted_fullname]\nメールアドレス： [restricted_mail_address]\n所属機関：[restricted_university_institution]\n研究題目：[restricted_research_title]\n申請データ：[restricted_data_name]\n申請年月日：[restricted_application_date]\n\n[restricted_site_name_ja]（[restricted_site_url]）にアクセスしていただき、画面左上からログインしていただけますと、「ワークフロー」タブが現れます。ここから上記の申請内容をご確認ください。「承認」または「却下」のボタンをクリックしてください。\n\nこのメールに心当たりのない方は、[restricted_site_name_ja] までご連絡ください。\n\n[restricted_site_name_ja]：[restricted_site_url]\n問い合わせ窓口：[restricted_site_mail]\n\n----------------------------------------------------------------------------------\n\nThis is a message from [restricted_site_name_en].\nWe received the below application.\n\nApplication No.：[restricted_activity_id]\nName：[restricted_fullname]\nE-mail：[restricted_mail_address]\nAffiliation：[restricted_university_institution]\nTitle of research：[restricted_research_title]\nDataset requested ：[restricted_data_name]\nApplication date：[restricted_application_date]\n\n\nPlease access [restricted_site_name_en]（[restricted_site_url]） and log in from the upper left corner of the screen, and the [Workflow] tab will appear. From here, please confirm the above application by clicking on “approve” or “reject”.\n\nIf you received this message in error, please notify the [restricted_site_name_en]\n\n[restricted_site_name_en]：[restricted_site_url]\nE-mail：[restricted_site_mail]	t
4	利用申請の承認のお知らせ／Your application was approved	[restricted_site_name_ja]です。\n\n下記の利用申請を承認しました。\n\n申請番号： [restricted_activity_id]\n登録者名： [restricted_fullname]\nメールアドレス： [restricted_mail_address]\n所属機関：[restricted_university_institution]\n研究題目：[restricted_research_title]\n申請データ：[restricted_data_name]\n申請年月日：[restricted_application_date]\n\nデータは、下記アドレスよりダウンロードすることができます。\n\n[restricted_download_link]\n\n当日より[restricted_expiration_date][restricted_expiration_date_ja]日後まで有効です。ダウンロード期限を過ぎると、再申請が必要です。\n\nこのメールは自動送信されているので返信しないでください。\nこのメールに心当たりのない方は、[restricted_site_name_ja]までご連絡ください。\n\n[restricted_site_name_ja]：[restricted_site_url]\n問い合わせ窓口：[restricted_site_mail]\n\n----------------------------------------------------------------------------------\n\nThis is a message from [restricted_site_name_en].\nYour application below has been approved.\n\nApplication No.：[restricted_activity_id]\nName：[restricted_fullname]\nE-mail：[restricted_mail_address]\nAffiliation：[restricted_university_institution]\nTitle of research：[restricted_research_title]\nDataset requested ：[restricted_data_name]\nApplication date：[restricted_application_date]\n\nThe data can be downloaded from the address below.\n\n[restricted_download_link]\n\nIt is valid from that day until the day after [restricted_expiration_date][restricted_expiration_date_en]. You will need to resubmit your application once the link becomes unavailable.\n\nPlease do not reply to this email as it has been sent automatically.\nIf you received this message in error, please notify the [restricted_site_name_en].\n\n[restricted_site_name_en]：[restricted_site_url]\nE-mail：[restricted_site_mail]	t
5	利用申請の審査結果について／The results of the review of your application	[restricted_site_name_ja]です。\n\n下記の利用申請を却下しました。\n\n申請番号： [restricted_activity_id]\n登録者名： [restricted_fullname]\nメールアドレス： [restricted_mail_address]\n所属機関：[restricted_university_institution]\n研究題目：[restricted_research_title]\n申請データ：[restricted_data_name]\n申請年月日：[restricted_application_date]\n\nこのメールは自動送信されているので返信しないでください。\nお問い合わせは下記までお願いします。また、このメールに心当たりのない方は、[restricted_site_name_ja] までご連絡ください。\n\n[restricted_site_name_ja]：[restricted_site_url]\n問い合わせ窓口：[restricted_site_mail]\n\n----------------------------------------------------------------------------------\n\nThis is a message from [restricted_site_name_en].\nYour application below has been rejected.\n\nApplication No.：[restricted_activity_id]\nName：[restricted_fullname]\nE-mail：[restricted_mail_address]\nAffiliation：[restricted_university_institution]\nTitle of research：[restricted_research_title]\nDataset requested ：[restricted_data_name]\nApplication date：[restricted_application_date]\n\nPlease do not reply to this email as it has been sent automatically.\nPlease direct all inquiries to the following address.\nAlso, if you received this message in error, please notify [restricted_site_name_en].\n\n[restricted_site_name_en]：[restricted_site_url]\nE-mail：[restricted_site_mail]	t
6	利用報告の登録のお願い／Request for register Data Usage Report	[restricted_site_name_ja]です。\n下記で申請いただいデータについてダウンロードされたことを確認しました。\n\n申請番号： [restricted_usage_activity_id]\n登録者名： [restricted_fullname]\nメールアドレス： [restricted_mail_address]\n所属機関：[restricted_university_institution]\n研究題目：[restricted_research_title]\n申請データ：[restricted_data_name]\n申請年月日：[restricted_application_date]\n\nダウンロードしたデータについて、下記のリンクから利用報告の登録をお願いします。\n\n[usage_report_url]\n\nこのメールは自動送信されているので返信しないでください。\nお問い合わせは下記までお願いします。また、このメールに心当たりのない方は、[restricted_site_name_ja]までご連絡ください。\n\n[restricted_site_name_ja]：[restricted_site_url]\n問い合わせ窓口：[restricted_site_mail]\n\n----------------------------------------------------------------------------------\n\nThis is a message from [restricted_site_name_en].\nWe have confirmed that the dataset which you registered at below has been downloaded.\n\nApplication No.：[restricted_usage_activity_id]\nName：[restricted_fullname]\nE-mail：[restricted_mail_address]\nAffiliation：[restricted_university_institution]\nTitle of research：[restricted_research_title]\nDataset requested ：[restricted_data_name]\nApplication date：[restricted_application_date]\n\nFor the downloaded data, please register the Data Usage Report by the link below.\n\n[usage_report_url]\n\nPlease do not reply to this email as it has been sent automatically.\nPlease direct all inquiries to the following address.\nAlso, if you received this message in error, please notify [restricted_site_name_en].\n\n[restricted_site_name_en]：[restricted_site_url]\nE-mail：[restricted_site_mail]\n	t
7	利用報告の登録のお願い／Request for register Data Usage Report	[restricted_site_name_ja]です。\n現時点で、下記の利用報告が登録されていません\n\n報告番号：[restricted_activity_id]\n登録者名：[restricted_fullname]\nメールアドレス：[restricted_mail_address]\n所属機関：[restricted_university_institution]\n利用データ：[restricted_data_name]\nデータダウンロード日：[data_download_date]\n\n下記のリンクから利用報告の登録をお願いします。\n\n[usage_report_url]\n\nこのメールは自動送信されているので返信しないでください。\nお問い合わせは下記までお願いします。また、このメールに心当たりのない方は、[restricted_site_name_ja]までご連絡ください。\n\n[restricted_site_name_ja]：[restricted_site_url]\n問い合わせ窓口：[restricted_site_mail]\n\n----------------------------------------------------------------------------------\n\nThis is a message from [restricted_site_name_en].\nAt this time, the Data Usage Report below has not been registered.\n\nUsage Report No.：[restricted_activity_id]\nName：[restricted_fullname]\nE-mail：[restricted_mail_address]\nAffiliation：[restricted_university_institution]\nUsage Dataset：[restricted_data_name]\nDownload date：[data_download_date]\n\nPlease register the Data Usage Report from the link below.\n\n[usage_report_url]\n\nPlease do not reply to this email as it has been sent automatically.\nPlease direct all inquiries to the following address.\nAlso, if you received this message in error, please notify [restricted_site_name_en].\n\n[restricted_site_name_en]：[restricted_site_url]\nE-mail：[restricted_site_mail]\n	t
\.


--
-- Name: mail_templates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invenio
--

SELECT pg_catalog.setval('public.mail_templates_id_seq', 7, true);


--
-- PostgreSQL database dump complete
--

