# -*- coding: utf-8 -*-
#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.

# Elasticsearch 6.8.23 for arm64.
# The official docker.elastic.co image used by ./Dockerfile is amd64-only for the
# 6.x series (arm64 images exist only from 7.8+), so here Elasticsearch is installed
# from the release tarball on top of an arm64-native JDK image. Plugin / keystore /
# S3 setup is delegated to scripts/provision-elasticsearch.sh to stay in sync with
# the main ./Dockerfile.
FROM arm64v8/openjdk:8-jdk-buster

WORKDIR /usr/share/elasticsearch
ARG ELASTICSEARCH_S3_ACCESS_KEY
ARG ELASTICSEARCH_S3_SECRET_KEY
ARG ELASTICSEARCH_S3_ENDPOINT
ARG ELASTICSEARCH_S3_BUCKET
ENV ELASTICSEARCH_S3_ACCESS_KEY=${ELASTICSEARCH_S3_ACCESS_KEY}
ENV ELASTICSEARCH_S3_SECRET_KEY=${ELASTICSEARCH_S3_SECRET_KEY}
ENV ELASTICSEARCH_S3_ENDPOINT=${ELASTICSEARCH_S3_ENDPOINT}
ENV ELASTICSEARCH_S3_BUCKET=${ELASTICSEARCH_S3_BUCKET}

# Install Elasticsearch 6.8.23 from the release tarball (arm64-native JDK base image).
# buster has been moved to archive.debian.org, so repoint apt before updating.
RUN sed -i 's/deb.debian.org/archive.debian.org/g; s/security.debian.org/archive.debian.org/g' /etc/apt/sources.list && \
    groupadd -g 1000 elasticsearch && \
    useradd -u 1000 -g elasticsearch elasticsearch && \
    apt-get -o Acquire::Check-Valid-Until=false update && \
    apt-get install -y curl nano && \
    curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.23.tar.gz && \
    tar -xf elasticsearch-6.8.23.tar.gz --strip-components=1 && \
    rm -f elasticsearch-6.8.23.tar.gz && \
    echo 'xpack.security.enabled: false' >> config/elasticsearch.yml && \
    echo 'xpack.ml.enabled: false' >> config/elasticsearch.yml && \
    echo 'http.host: 0.0.0.0' >> config/elasticsearch.yml && \
    echo 'transport.host: 0.0.0.0' >> config/elasticsearch.yml && \
    mkdir -p backups data && \
    chown -R elasticsearch:elasticsearch /usr/share/elasticsearch

# Install Elasticsearch plugins / keystore / S3 credentials via the shared script.
# provision-elasticsearch.sh selects its Docker branch by detecting /.dockerenv,
# which BuildKit does not create during build, so materialize it for this stage.
COPY scripts/provision-elasticsearch.sh /tmp/
COPY elasticsearch/dic/character/kui.txt /usr/share/elasticsearch/config
RUN touch /.dockerenv && \
    /tmp/provision-elasticsearch.sh && \
    chown -R elasticsearch:elasticsearch /usr/share/elasticsearch

USER elasticsearch
ENV discovery.type=single-node
CMD ["/usr/share/elasticsearch/bin/elasticsearch"]
