FROM ubuntu:focal AS nginx-with-shib

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /tmp

RUN apt-get update -y && \
    apt-get install -y wget curl gnupg2 ca-certificates lsb-release unzip uuid-dev dpkg-dev
RUN echo "deb http://nginx.org/packages/ubuntu focal nginx" | tee /etc/apt/sources.list.d/nginx.list
RUN echo "deb-src http://nginx.org/packages/ubuntu focal nginx" | tee -a /etc/apt/sources.list.d/nginx.list
RUN curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -
RUN apt-get update -y && \
    apt-get source -y nginx=1.20.1 && \
    apt-get build-dep -y nginx=1.20.1

# https://github.com/samizdatco/nginx-http-auth-digest
RUN wget "https://github.com/samizdatco/nginx-http-auth-digest/archive/master.zip" -O nginx-http-auth-digest.zip
# https://github.com/nginx-shib/nginx-http-shibboleth
RUN wget "https://github.com/nginx-shib/nginx-http-shibboleth/archive/v2.0.1.tar.gz" -O nginx-http-shibboleth-2.0.1.tar.gz
RUN wget "https://github.com/openresty/headers-more-nginx-module/archive/v0.33.tar.gz" -O headers-more-nginx-module-0.33.tar.gz
RUN wget "https://github.com/FRiCKLE/ngx_cache_purge/archive/2.3.tar.gz" -O ngx_cache_purge-2.3.tar.gz

RUN unzip nginx-http-auth-digest.zip && \
  tar zxf nginx-http-shibboleth-2.0.1.tar.gz && \
  tar zxf headers-more-nginx-module-0.33.tar.gz && \
  tar zxf ngx_cache_purge-2.3.tar.gz

RUN sed -i "s#--modules-path=/usr/lib/nginx/modules#--modules-path=/usr/lib/nginx/modules --add-module=/tmp/headers-more-nginx-module-0.33 --add-module=/tmp/nginx-http-shibboleth-2.0.1 --add-module=/tmp/nginx-http-auth-digest-master --add-module=/tmp/ngx_cache_purge-2.3 #g" nginx-1.20.1/debian/rules
RUN cd nginx-1.20.1 && dpkg-buildpackage -b

FROM ubuntu:focal AS nginx-stage_1

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y openssl wget curl unzip supervisor shibboleth-sp-common shibboleth-sp-utils fcgiwrap python3-requests

WORKDIR /tmp
# dpkg-buildpackage names the .deb after the build host architecture
# (amd64 / arm64), so match it with a wildcard instead of hard-coding it.
COPY --from=nginx-with-shib /tmp/nginx_1.20.1-1~focal_*.deb ./
COPY --from=nginx-with-shib /tmp/nginx-dbg_1.20.1-1~focal_*.deb ./
RUN dpkg -i nginx_1.20.1-1~focal_*.deb


ADD supervisord.conf /etc/supervisor/supervisord.conf
# supervisord.conf points shibauthorizer / shibresponder at the x86_64
# library directory. Rewrite it for the build architecture (e.g. aarch64).
RUN sed -i "s#/usr/lib/x86_64-linux-gnu/shibboleth/#/usr/lib/$(uname -m)-linux-gnu/shibboleth/#g" \
    /etc/supervisor/supervisord.conf
ADD shibboleth2.xml /etc/shibboleth/shibboleth2.xml
ADD attribute-map.xml /etc/shibboleth/attribute-map.xml
ADD attribute-policy.xml /etc/shibboleth/attribute-policy.xml

ADD ./keys/server.crt /etc/shibboleth/server.crt
ADD ./keys/server.key /etc/shibboleth/server.key


RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf
COPY weko-ams.conf /etc/nginx/conf.d/weko.conf
ADD nginx.conf /etc/nginx/nginx.conf
ADD ./keys/server.crt /etc/nginx/server.crt
ADD ./keys/server.key /etc/nginx/server.key
ADD ./idp-metadata.xml /etc/shibboleth/idp-metadata.xml
ADD ./orthros-idp-metadata.xml /etc/shibboleth/orthros-idp-metadata.xml
ADD ./htpasswd /etc/nginx/.htpasswd
ADD ./htdigest /etc/nginx/.htdigest
ADD redirect_list.map /etc/nginx/redirect_list.map

RUN chmod 400 /etc/nginx/server.key

RUN mkdir  /usr/share/nginx/html/secure
ADD ./login.py /usr/share/nginx/html/secure/login.py
RUN chmod 755 /usr/share/nginx/html/secure/login.py

ADD ./shib_clear_headers /etc/nginx/shib_clear_headers
ADD ./shib_fastcgi_params /etc/nginx/shib_fastcgi_params

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get update && apt-get install -y nodejs
ADD ./ams/weko-frontend /usr/local/weko-frontend
WORKDIR /usr/local/weko-frontend
RUN npm install
RUN export NODE_OPTIONS=--max_old_space_size=4096
RUN npm run build
RUN npm install -g pm2
EXPOSE 3000

ADD ./startup.sh /usr/local
ADD ./ecosystem.config.js /usr/local
RUN chmod +x /usr/local/startup.sh
RUN chmod +x /usr/local/ecosystem.config.js

CMD ["/usr/local/startup.sh"]
