{% include 'misc/header.py' %}
notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release DEPLOY=true
  - REQUIREMENTS=devel

python:
  - "3.5"

before_install:
  - "nvm install 6; nvm use 6"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: TODO:PYPISECUREHASH
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "3.5"
    repo: {{ cookiecutter.github_repo }}
    condition: $DEPLOY = true
