#!/usr/bin/env python3
"""Generate a compact database reference in Markdown."""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "database_inventory.md"

TABLE_RE = re.compile(r"__tablename__\s*=\s*['\"]([^'\"]+)['\"]")
CREATE_TABLE_RE = re.compile(
    r"CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+(?:public\.)?([A-Za-z0-9_]+)",
    re.IGNORECASE,
)
OP_CREATE_TABLE_RE = re.compile(r"op\.create_table\(\s*['\"]([^'\"]+)['\"]")


def relpath(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def scan_model_tables() -> Dict[str, List[Tuple[str, List[str]]]]:
    per_module: Dict[str, List[Tuple[str, List[str]]]] = defaultdict(list)
    for path in sorted(ROOT.glob("modules/*/*/models.py")):
        relative_path = relpath(path)
        text = path.read_text(encoding="utf-8")
        tables = sorted(set(TABLE_RE.findall(text)))
        if tables:
            per_module[relative_path.split("/")[1]].append((relative_path, tables))
    return dict(sorted(per_module.items()))


def scan_alembic_tables() -> Dict[str, List[Tuple[str, List[str]]]]:
    per_module: Dict[str, List[Tuple[str, List[str]]]] = defaultdict(list)
    for path in sorted(ROOT.glob("modules/*/*/alembic/*.py")):
        relative_path = relpath(path)
        if "/tests/" in relative_path:
            continue
        text = path.read_text(encoding="utf-8")
        tables = sorted(set(OP_CREATE_TABLE_RE.findall(text)))
        per_module[relative_path.split("/")[1]].append((relative_path, tables))
    return dict(sorted(per_module.items()))


def scan_sql_tables(base: Path) -> List[Tuple[str, List[str]]]:
    results: List[Tuple[str, List[str]]] = []
    for path in sorted(base.glob("*.sql")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        tables = sorted(set(CREATE_TABLE_RE.findall(text)))
        results.append((relpath(path), tables))
    return results


def write_bullet_block(
    lines: List[str], heading: str, entries: Iterable[Tuple[str, List[str]]]
) -> None:
    lines.append(f"### {heading}")
    lines.append("")
    for path, tables in entries:
        table_text = ", ".join(f"`{name}`" for name in tables) if tables else "None detected"
        lines.append(f"- `{path}`")
        lines.append(f"  Tables: {table_text}")
    lines.append("")


def generate() -> None:
    model_tables = scan_model_tables()
    alembic_tables = scan_alembic_tables()
    ddl_tables = scan_sql_tables(ROOT / "postgresql" / "ddl")
    update_tables = scan_sql_tables(ROOT / "postgresql" / "update")

    lines: List[str] = []
    lines.append("# Database Inventory")
    lines.append("")
    lines.extend(
        [
            "<!-- This file is generated by `python3 scripts/generate_db_reference.py`. -->",
            "",
            "This page is a compact index for developers who need to inspect the DB structure",
            "without reading the full schema dump first.",
            "",
            "## How to use this page",
            "",
            "* Start here to find the relevant module, migration, or SQL file.",
            "* Use `docs/database_guide.md` for the workflow and lookup order.",
            "* Use `docs/source/developer/database.rst` only when you need the full schema dump.",
            "",
        ]
    )

    lines.append("## SQLAlchemy models by module")
    lines.append("")
    lines.append(f"- Modules with model definitions: {len(model_tables)}")
    lines.append("")
    for module_name, entries in model_tables.items():
        write_bullet_block(lines, module_name, entries)

    lines.append("## Alembic migrations by module")
    lines.append("")
    lines.append(f"- Modules with Alembic migrations: {len(alembic_tables)}")
    lines.append("")
    for module_name, entries in alembic_tables.items():
        write_bullet_block(lines, module_name, entries)

    lines.append("## PostgreSQL DDL files")
    lines.append("")
    write_bullet_block(lines, "postgresql/ddl", ddl_tables)

    lines.append("## PostgreSQL update files")
    lines.append("")
    write_bullet_block(lines, "postgresql/update", update_tables)

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {relpath(OUTPUT)}")


if __name__ == "__main__":
    generate()
