--
-- PostgreSQL database dump
--

-- Dumped from database version 12.7 (Debian 12.7-1.pgdg100+1)
-- Dumped by pg_dump version 12.7 (Debian 12.7-1.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.index DROP CONSTRAINT uix_position CASCADE;
ALTER TABLE ONLY public.index DROP CONSTRAINT pk_index CASCADE;
ALTER TABLE public.index ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.index_id_seq CASCADE;
DROP TABLE public.index CASCADE;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: index; Type: TABLE; Schema: public; Owner: invenio
--

CREATE TABLE public.index (
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    parent bigint NOT NULL,
    "position" integer NOT NULL,
    index_name text,
    index_name_english text NOT NULL,
    index_link_name text,
    index_link_name_english text NOT NULL,
    harvest_spec text,
    index_link_enabled boolean NOT NULL,
    comment text,
    more_check boolean NOT NULL,
    display_no integer NOT NULL,
    harvest_public_state boolean NOT NULL,
    display_format text,
    image_name text NOT NULL,
    public_state boolean NOT NULL,
    public_date timestamp without time zone,
    recursive_public_state boolean,
    rss_status boolean,
    coverpage_state boolean,
    recursive_coverpage_check boolean,
    browsing_role text,
    recursive_browsing_role boolean,
    contribute_role text,
    recursive_contribute_role boolean,
    browsing_group text,
    recursive_browsing_group boolean,
    contribute_group text,
    recursive_contribute_group boolean,
    owner_user_id integer,
    item_custom_sort jsonb,
    biblio_flag boolean,
    online_issn text
);


ALTER TABLE public.index OWNER TO invenio;

--
-- Name: index_id_seq; Type: SEQUENCE; Schema: public; Owner: invenio
--

CREATE SEQUENCE public.index_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.index_id_seq OWNER TO invenio;

--
-- Name: index_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: invenio
--

ALTER SEQUENCE public.index_id_seq OWNED BY public.index.id;


--
-- Name: index id; Type: DEFAULT; Schema: public; Owner: invenio
--

ALTER TABLE ONLY public.index ALTER COLUMN id SET DEFAULT nextval('public.index_id_seq'::regclass);


--
-- Data for Name: index; Type: TABLE DATA; Schema: public; Owner: invenio
--

INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:44:36.200158', '2021-05-22 02:44:42.33875', 1621651476208, 1621651246223, 0, 'Index B-2-1', 'Index B-2-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:44:45.21455', '2021-05-22 02:44:53.247179', 1621651485213, 1621651246223, 1, 'Index B-2-2(Private)', 'Index B-2-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:45:03.204794', '2021-05-22 02:45:30.246997', 1621651503213, 0, 2, 'Index C', 'Index C', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:45:34.271126', '2021-05-22 02:45:43.239981', 1621651534211, 0, 3, 'Index D(Private)', 'Index D(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:40:00.210313', '2021-05-22 02:40:05.245356', 1621651200227, 0, 0, 'Index A', 'Index A', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:40:08.208117', '2021-05-22 02:40:12.233723', 1621651208226, 0, 1, 'Index B(Private)', 'Index B(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:40:15.210221', '2021-05-22 02:40:21.233223', 1621651215223, 1621651200227, 0, 'Index A-1', 'Index A-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:40:24.217641', '2021-05-22 02:40:28.306997', 1621651224224, 1621651200227, 1, 'Index A-2(Private)', 'Index A-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:40:37.212684', '2021-05-22 02:40:43.29506', 1621651237227, 1621651208226, 0, 'Index B-1', 'Index B-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:40:46.277892', '2021-05-22 02:40:50.310102', 1621651246223, 1621651208226, 1, 'Index B-2(Private)', 'Index B-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:40:59.205863', '2021-05-22 02:41:05.211566', 1621651259224, 1621651215223, 0, 'Index A-1-1', 'Index A-1-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:41:08.202752', '2021-05-22 02:41:12.258592', 1621651268223, 1621651215223, 1, 'Index A-1-2(Private)', 'Index A-1-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:41:37.211433', '2021-05-22 02:41:43.209211', 1621651297224, 1621651224224, 0, 'Index A-2-1', 'Index A-2-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:41:46.208977', '2021-05-22 02:42:39.238328', 1621651306220, 1621651224224, 1, 'Index A-2-2(Private)', 'Index A-2-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:42:43.208538', '2021-05-22 02:42:49.216619', 1621651363208, 1621651237227, 0, 'Index B-1-1', 'Index B-1-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:44:11.205763', '2021-05-22 02:44:32.400856', 1621651451210, 1621651237227, 1, 'Index B-1-2(Private)', 'Index B-1-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:45:47.211159', '2021-05-22 02:45:53.251071', 1621651547213, 1621651503213, 0, 'Index C-1', 'Index C-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:45:56.206566', '2021-05-22 02:46:10.251903', 1621651556212, 1621651503213, 1, 'Index C-2(Private)', 'Index C-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:46:14.203773', '2021-05-22 02:46:20.321425', 1621651574211, 1621651534211, 0, 'Index D-1', 'Index D-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:46:24.215616', '2021-05-22 02:46:42.242423', 1621651584214, 1621651534211, 1, 'Index D-2(Private)', 'Index D-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:46:46.21046', '2021-05-22 02:46:52.221306', 1621651606213, 1621651547213, 0, 'Index C-1-1', 'Index C-1-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:46:56.215866', '2021-05-22 02:47:05.243013', 1621651616212, 1621651547213, 1, 'Index C-1-2(Private)', 'Index C-1-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:47:09.219627', '2021-05-22 02:47:15.226574', 1621651629214, 1621651556212, 0, 'Index C-2-1', 'Index C-2-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:47:18.269397', '2021-05-22 02:47:33.266795', 1621651638214, 1621651556212, 1, 'Index C-2-2(Private)', 'Index C-2-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:47:37.215943', '2021-05-22 02:47:43.241566', 1621651657214, 1621651574211, 0, 'Index D-1-1', 'Index D-1-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:47:47.20912', '2021-05-22 02:47:54.247445', 1621651667214, 1621651574211, 1, 'Index D-1-2(Private)', 'Index D-1-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:47:58.208689', '2021-05-22 02:48:04.2181', 1621651678213, 1621651584214, 0, 'Index D-2-1', 'Index D-2-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:48:09.208395', '2021-05-22 02:48:22.247354', 1621651689213, 1621651584214, 1, 'Index D-2-2(Private)', 'Index D-2-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:48:35.208219', '2021-05-22 02:48:47.247253', 1621651715217, 0, 4, 'Index E(Embargo)', 'Index E(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:48:50.216131', '2021-05-22 02:48:56.229829', 1621651730217, 1621651715217, 0, 'Index E-1', 'Index E-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:48:59.210562', '2021-05-22 02:49:12.241839', 1621651739216, 1621651715217, 1, 'Index E-2(Private)', 'Index E-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:49:16.244996', '2021-05-22 02:49:35.27698', 1621651756217, 1621651715217, 2, 'Index E-3(Embargo)', 'Index E-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:49:38.267116', '2021-05-22 02:49:44.236006', 1621651778216, 1621651730217, 0, 'Index E-1-1', 'Index E-1-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:49:47.229801', '2021-05-22 02:49:57.243634', 1621651787219, 1621651730217, 1, 'Index E-1-2(Private)', 'Index E-1-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:50:01.214329', '2021-05-22 02:50:14.248087', 1621651801218, 1621651730217, 2, 'Index E-1-3(Embargo)', 'Index E-1-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:50:18.220217', '2021-05-22 02:50:24.16683', 1621651818218, 1621651739216, 0, 'Index E-2-1', 'Index E-2-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:50:25.293649', '2021-05-22 02:50:38.316279', 1621651825290, 1621651739216, 1, 'Index E-2-2(Private)', 'Index E-2-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:50:41.21811', '2021-05-22 02:50:50.239741', 1621651841218, 1621651739216, 2, 'Index E-2-3(Embargo)', 'Index E-2-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:50:54.213711', '2021-05-22 02:51:00.227011', 1621651854221, 1621651756217, 0, 'Index E-3-1', 'Index E-3-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:51:03.224574', '2021-05-22 02:51:15.240692', 1621651863219, 1621651756217, 1, 'Index E-3-2(Private)', 'Index E-3-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:51:26.230337', '2021-05-22 02:51:44.248381', 1621651886218, 1621651756217, 2, 'Index E-3-3(Embargo)', 'Index E-3-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:51:47.209638', '2021-05-22 02:51:59.244681', 1621651907220, 0, 5, 'Index F(Embargo)', 'Index F(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:52:02.211676', '2021-05-22 02:52:08.234184', 1621651922219, 1621651907220, 0, 'Index F-1', 'Index F-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:52:11.210484', '2021-05-22 02:52:22.237588', 1621651931219, 1621651907220, 1, 'Index F-2(Private)', 'Index F-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:52:26.204412', '2021-05-22 02:52:37.360165', 1621651946219, 1621651907220, 2, 'Index F-3(Embargo)', 'Index F-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:52:43.213612', '2021-05-22 02:52:49.238439', 1621651963220, 1621651922219, 0, 'Index F-1-1', 'Index F-1-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:52:54.214249', '2021-05-22 02:53:03.234886', 1621651974222, 1621651922219, 1, 'Index F-1-2(Private)', 'Index F-1-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:53:07.21037', '2021-05-22 02:53:18.23528', 1621651987221, 1621651922219, 2, 'Index F-1-3(Embargo)', 'Index F-1-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:53:22.210805', '2021-05-22 02:53:28.2375', 1621652002221, 1621651931219, 0, 'Index F-2-1', 'Index F-2-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:53:31.209909', '2021-05-22 02:53:35.314188', 1621652011220, 1621651931219, 1, 'Index F-2-2(Private)', 'Index F-2-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:53:38.222711', '2021-05-22 02:54:04.303773', 1621652018223, 1621651931219, 2, 'Index F-2-3(Embargo)', 'Index F-2-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:54:08.219908', '2021-05-22 02:54:14.252842', 1621652048224, 1621651946219, 0, 'Index F-3-1', 'Index F-3-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:54:17.230461', '2021-05-22 02:54:27.255897', 1621652057221, 1621651946219, 1, 'Index F-3-2(Private)', 'Index F-3-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:54:31.217272', '2021-05-22 02:54:44.242804', 1621652071223, 1621651946219, 2, 'Index F-3-3(Embargo)', 'Index F-3-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:54:47.20349', '2021-05-22 02:55:17.232122', 1621652087223, 1621651200227, 2, 'Index A-3(Embargo)', 'Index A-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:55:21.241611', '2021-05-22 02:55:27.244135', 1621652121223, 1621652087223, 0, 'Index A-3-1', 'Index A-3-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:55:31.208976', '2021-05-22 02:55:35.247222', 1621652131223, 1621652087223, 1, 'Index A-3-2(Private)', 'Index A-3-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:55:38.265562', '2021-05-22 02:56:04.249069', 1621652138225, 1621652087223, 2, 'Index A-3-3(Embargo)', 'Index A-3-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:56:08.214806', '2021-05-22 02:56:19.244536', 1621652168226, 1621651215223, 2, 'Index A-1-3(Embargo)', 'Index A-1-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:56:23.206744', '2021-05-22 02:56:35.246359', 1621652183223, 1621651224224, 2, 'Index A-2-3(Embargo)', 'Index A-2-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:56:39.205377', '2021-05-22 02:56:49.269102', 1621652199225, 1621651208226, 2, 'Index B-3(Embargo)', 'Index B-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:56:53.208862', '2021-05-22 02:56:59.229844', 1621652213225, 1621652199225, 0, 'Index B-3-1', 'Index B-3-1', '', 'New Index', '', false, '', false, 5, true, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:57:03.213038', '2021-05-22 02:57:13.246408', 1621652223228, 1621652199225, 1, 'Index B-3-2(Private)', 'Index B-3-2(Private)', '', 'New Index', '', false, '', false, 5, true, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:57:17.206303', '2021-05-22 02:57:28.433798', 1621652237227, 1621652199225, 2, 'Index B-3-3(Embargo)', 'Index B-3-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:57:32.210629', '2021-05-22 02:57:49.231174', 1621652252229, 1621651237227, 2, 'Index B-1-3(Embargo)', 'Index B-1-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:57:52.211052', '2021-05-22 02:58:03.240331', 1621652272227, 1621651246223, 2, 'Index B-2-3(Embargo)', 'Index B-2-3(Embargo)', '', 'New Index', '', false, '', false, 5, true, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:58:07.208825', '2021-05-22 02:58:24.242952', 1621652287228, 1621651503213, 2, 'Index C-3(Embargo)', 'Index C-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:58:28.291323', '2021-05-22 02:58:34.246248', 1621652308230, 1621652287228, 0, 'Index C-3-1', 'Index C-3-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:58:38.23489', '2021-05-22 02:58:45.254107', 1621652318229, 1621652287228, 1, 'Index C-3-2(Private)', 'Index C-3-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:58:48.212426', '2021-05-22 02:58:58.24313', 1621652328229, 1621652287228, 2, 'Index C-3-3(Embargo)', 'Index C-3-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:59:01.233621', '2021-05-22 02:59:08.248685', 1621652341231, 1621651547213, 2, 'Index C-1-3(Embargo)', 'Index C-1-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:59:12.2123', '2021-05-22 02:59:21.237421', 1621652352229, 1621651556212, 2, 'Index C-2-3(Embargo)', 'Index C-2-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:59:26.248038', '2021-05-22 02:59:35.235567', 1621652366229, 1621651534211, 2, 'Index D-3(Embargo)', 'Index D-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:59:38.2171', '2021-05-22 02:59:44.243492', 1621652378232, 1621652366229, 0, 'Index D-3-1', 'Index D-3-1', '', 'New Index', '', false, '', false, 5, false, '1', '', true, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 02:59:48.24304', '2021-05-22 02:59:59.240151', 1621652388230, 1621652366229, 1, 'Index D-3-2(Private)', 'Index D-3-2(Private)', '', 'New Index', '', false, '', false, 5, false, '1', '', false, NULL, false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 03:00:03.219503', '2021-05-22 03:00:12.301827', 1621652403231, 1621652366229, 2, 'Index D-3-3(Embargo)', 'Index D-3-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 03:00:16.240192', '2021-05-22 03:00:35.248639', 1621652416229, 1621651574211, 2, 'Index D-1-3(Embargo)', 'Index D-1-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');
INSERT INTO public.index (created, updated, id, parent, "position", index_name, index_name_english, index_link_name, index_link_name_english, harvest_spec, index_link_enabled, comment, more_check, display_no, harvest_public_state, display_format, image_name, public_state, public_date, recursive_public_state, rss_status, coverpage_state, recursive_coverpage_check, browsing_role, recursive_browsing_role, contribute_role, recursive_contribute_role, browsing_group, recursive_browsing_group, contribute_group, recursive_contribute_group, owner_user_id, item_custom_sort, biblio_flag, online_issn) VALUES ('2021-05-22 03:00:38.246647', '2021-05-22 03:01:15.229449', 1621652438231, 1621651584214, 2, 'Index D-2-3(Embargo)', 'Index D-2-3(Embargo)', '', 'New Index', '', false, '', false, 5, false, '1', '', true, '2024-03-31 00:00:00', false, false, false, false, '3,-98,-99', false, '1,2,3,4,-98,-99', false, '', false, '', false, 1, '{}', false, '');


--
-- Name: index_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invenio
--

SELECT pg_catalog.setval('public.index_id_seq', 1, false);


--
-- Name: index pk_index; Type: CONSTRAINT; Schema: public; Owner: invenio
--

ALTER TABLE ONLY public.index
    ADD CONSTRAINT pk_index PRIMARY KEY (id);


--
-- Name: index uix_position; Type: CONSTRAINT; Schema: public; Owner: invenio
--

ALTER TABLE ONLY public.index
    ADD CONSTRAINT uix_position UNIQUE (parent, "position");


--
-- PostgreSQL database dump complete
--

