#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""update."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3fd78b0175'
down_revision = '9d6b2ebed7eb'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_journal_id'), 'journal', ['id'])
    op.create_unique_constraint(op.f('uq_journal_export_processing_id'), 'journal_export_processing', ['id'])
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_journal_export_processing_id'), 'journal_export_processing', type_='unique')
    op.drop_constraint(op.f('uq_journal_id'), 'journal', type_='unique')
    # ### end Alembic commands ###
